sudo: required
services:
- docker
before_install:
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
    - docker --version # for verification
language: generic
jobs:
  include:
    - stage: build docker images
      env:
        - TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
        - BASE_X86=jfloff/alpine-python
        - BASE_ARM=resin/raspberry-pi-alpine-python
      script:
      - echo $TAG
      # Unittest
      - docker run --rm -v $(pwd):/usr/src -ti jfloff/alpine-python bash -c 'cd /usr/src && pip3 install -r requirements.txt &&  python3 -m unittest' 
      # x86 build
      - docker build --build-arg BASE_IMAGE=$BASE_X86 -t sdelrio/hs110-exporter -f Dockerfile .
      # prepare qemu for arm build
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # build arm image
      - docker build --build-arg BASE_IMAGE=$BASE_ARM -t sdelrio/hs110-exporter-arm -f Dockerfile .
      - >
        if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
          TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
          docker tag sdelrio/hs110-exporter sdelrio/hs110-exporter:$TAG
          docker push sdelrio/hs110-exporter:$TAG
          docker push sdelrio/hs110-exporter
          docker tag sdelrio/hs110-exporter-arm sdelrio/hs110-exporter-arm:$TAG
          docker push sdelrio/hs110-exporter-arm:$TAG
          docker push sdelrio/hs110-exporter-arm
        fi

    - stage: test
      script:
      # test x86 image
      - docker run --rm -e "SHOWHELP=true" -ti sdelrio/hs110-exporter
      # prepare qemu for arm build
      - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      # test arm image
      - docker run --rm -e "SHOWHELP=true" -ti sdelrio/hs110-exporter-arm

